ant = float(input('Hvor mange cookies ønsker du å bake? '))
print('Antall cookies:', ant)
print('sukker (g):',round(400*ant/48, 1))
print('smør (g):', round(320*ant/48,1))
print('sjokolade (g):', round(500*ant/48,1))
print('egg:',round(2*ant/48,1))
print('hvetemel (g):',round(460*ant/48,1))
