print('Oppgave 1a')
print('Jeg elsker ITGK')
print()
print()
print('Oppgave 1b')
print('Norge')
print()
print('Areal(kv.km):', 385180)
print('Folketall (mill.)', 5.3)
print()
print()
print('Oppgave 1c')
print('"Jeg elsker ITGK!" ropte studenten da 1c funket')
print()
print()
print('Oppgave 1d')
print('Noen barn sto og hang ved lekeplassen.')
print('Diskusjonstemaet deres var noe uventet.')
print("- Hvorfor heter'e",'"Python"?')
print("- Var'e slanger som laget det? - Nei, Guido van Rossum.")
print('- Likte slanger kanskje da? - Nei, digga "Monty Python".')
print('- Hva er det? Et fjell?')
print("- Nei, engelsk komigruppe. Begynte i '", 69)
print("- Wow! Var'e fremdeles dinosaurer da?")
print()
print()
#Oppgave 1e)
#print('Hei")
print()
#I oppgave b) skrev jeg inn følgende
#print('Norge')
#print()
#print('Areal(kv.km):', 385180)
#print('Folketall (mill.)', 5.3)
print()
#I oppgave c) skrev jeg inn følgende
#print('"Jeg elsker ITGK!" ropte studenten da 1c funket')
print('Oppgave 1f)')
print("Heihei, jeg vil visst ikke kompilere jeg :(")
print('Halla, så "bra" du ser ut i dag')
print('Hei på deg')
print("Er ikke dette gøy?")

